# Generated by Django 3.2rc1 on 2021-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_image', models.ImageField(upload_to='')),
                ('movie_name', models.TextField()),
                ('movie_date', models.CharField(max_length=200)),
                ('movie_rating', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
